import type * as Monaco from "monaco-editor";

import draculaData from "monaco-themes/themes/Dracula.json";
import nightOwlData from "monaco-themes/themes/Night Owl.json";
import monokaiData from "monaco-themes/themes/Monokai.json";
import tomorrowNightData from "monaco-themes/themes/Tomorrow-Night.json";
import oceanicNextData from "monaco-themes/themes/Oceanic Next.json";
import cobalt2Data from "monaco-themes/themes/Cobalt2.json";
import solarizedDarkData from "monaco-themes/themes/Solarized-dark.json";
import githubDarkData from "monaco-themes/themes/GitHub Dark.json";
import tomorrowNightEightiesData from "monaco-themes/themes/Tomorrow-Night-Eighties.json";
import merbivoreData from "monaco-themes/themes/Merbivore Soft.json";
import githubLightData from "monaco-themes/themes/GitHub Light.json";
import solarizedLightData from "monaco-themes/themes/Solarized-light.json";
import tomorrowData from "monaco-themes/themes/Tomorrow.json";
import xcodeData from "monaco-themes/themes/Xcode_default.json";
import textmateData from "monaco-themes/themes/Textmate (Mac Classic).json";
import dawnData from "monaco-themes/themes/Dawn.json";
import cloudsData from "monaco-themes/themes/Clouds.json";
import iPlasticData from "monaco-themes/themes/iPlastic.json";
import kuroirData from "monaco-themes/themes/Kuroir Theme.json";
import dreamweaverData from "monaco-themes/themes/Dreamweaver.json";

type MonacoThemeData = Monaco.editor.IStandaloneThemeData;

export interface ColorTheme {
  id: string;
  name: string;
  type: "dark" | "light";
  monacoTheme: string;
  themeData: MonacoThemeData | null; // null = built-in Monaco theme, no defineTheme needed
  cssVars: Record<string, string>;
  previewBg: string;
  previewAccent: string;
}

// ─── Dark theme definitions ──────────────────────────────────────────────────

const DARK_SEMANTIC = {
  "--success-bg": "rgba(80,250,123,0.1)",
  "--success-border": "rgba(80,250,123,0.3)",
  "--success-text": "#50fa7b",
  "--error-bg": "rgba(255,85,85,0.1)",
  "--error-border": "rgba(255,85,85,0.3)",
  "--error-text": "#ff5555",
  "--warning-bg": "rgba(241,250,140,0.1)",
  "--warning-border": "#f1fa8c",
  "--warning-text": "#f1fa8c",
  "--blue-bg": "rgba(139,233,253,0.1)",
  "--blue-border": "rgba(139,233,253,0.3)",
  "--blue-text": "#8be9fd",
};

const LIGHT_SEMANTIC = {
  "--success-bg": "#f0fdf4",
  "--success-border": "#bbf7d0",
  "--success-text": "#166534",
  "--error-bg": "#fef2f2",
  "--error-border": "#fecaca",
  "--error-text": "#991b1b",
  "--warning-bg": "#fffbeb",
  "--warning-border": "#fcd34d",
  "--warning-text": "#92400e",
  "--blue-bg": "#eff6ff",
  "--blue-border": "#bfdbfe",
  "--blue-text": "#1e40af",
};

export const DARK_COLOR_THEMES: ColorTheme[] = [
  {
    id: "dracula",
    name: "Dracula",
    type: "dark",
    monacoTheme: "theme-dracula",
    themeData: draculaData,
    previewBg: "#282a36",
    previewAccent: "#bd93f9",
    cssVars: {
      "--bg-base": "#282a36",
      "--bg-secondary": "#21222c",
      "--bg-tertiary": "#44475a",
      "--bg-hover": "rgba(255,255,255,0.05)",
      "--bg-elevated": "#313244",
      "--border": "#44475a",
      "--border-color": "#44475a",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#6272a4",
      "--text-tertiary": "#44475a",
      "--primary": "#bd93f9",
      "--primary-dark": "#9f78f5",
      "--user-message-text": "#bd93f9",
      "--link-color": "#8be9fd",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "night-owl",
    name: "Night Owl",
    type: "dark",
    monacoTheme: "theme-night-owl",
    themeData: nightOwlData,
    previewBg: "#011627",
    previewAccent: "#82aaff",
    cssVars: {
      "--bg-base": "#011627",
      "--bg-secondary": "#01111d",
      "--bg-tertiary": "#0b2942",
      "--bg-hover": "rgba(255,255,255,0.04)",
      "--bg-elevated": "#012030",
      "--border": "#1d3b53",
      "--border-color": "#1d3b53",
      "--text-primary": "#d6deeb",
      "--text-secondary": "#637777",
      "--text-tertiary": "#1d3b53",
      "--primary": "#82aaff",
      "--primary-dark": "#6b8fe8",
      "--user-message-text": "#82aaff",
      "--link-color": "#22da6e",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    type: "dark",
    monacoTheme: "theme-monokai",
    themeData: monokaiData,
    previewBg: "#272822",
    previewAccent: "#a6e22e",
    cssVars: {
      "--bg-base": "#272822",
      "--bg-secondary": "#1e1f1c",
      "--bg-tertiary": "#3e3d32",
      "--bg-hover": "rgba(255,255,255,0.05)",
      "--bg-elevated": "#2d2e28",
      "--border": "#3e3d32",
      "--border-color": "#3e3d32",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#75715e",
      "--text-tertiary": "#49483e",
      "--primary": "#a6e22e",
      "--primary-dark": "#8bbf1a",
      "--user-message-text": "#e6db74",
      "--link-color": "#66d9e8",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "tomorrow-night",
    name: "Tomorrow Night",
    type: "dark",
    monacoTheme: "theme-tomorrow-night",
    themeData: tomorrowNightData,
    previewBg: "#1d1f21",
    previewAccent: "#81a2be",
    cssVars: {
      "--bg-base": "#1d1f21",
      "--bg-secondary": "#151617",
      "--bg-tertiary": "#282a2e",
      "--bg-hover": "rgba(255,255,255,0.04)",
      "--bg-elevated": "#222426",
      "--border": "#373b41",
      "--border-color": "#373b41",
      "--text-primary": "#c5c8c6",
      "--text-secondary": "#969896",
      "--text-tertiary": "#52545a",
      "--primary": "#81a2be",
      "--primary-dark": "#6a8da8",
      "--user-message-text": "#81a2be",
      "--link-color": "#b5bd68",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "oceanic-next",
    name: "Oceanic Next",
    type: "dark",
    monacoTheme: "theme-oceanic-next",
    themeData: oceanicNextData,
    previewBg: "#1b2b34",
    previewAccent: "#6699cc",
    cssVars: {
      "--bg-base": "#1b2b34",
      "--bg-secondary": "#12202a",
      "--bg-tertiary": "#343d46",
      "--bg-hover": "rgba(255,255,255,0.04)",
      "--bg-elevated": "#1f3240",
      "--border": "#343d46",
      "--border-color": "#343d46",
      "--text-primary": "#cdd3de",
      "--text-secondary": "#65737e",
      "--text-tertiary": "#343d46",
      "--primary": "#6699cc",
      "--primary-dark": "#5588bb",
      "--user-message-text": "#6699cc",
      "--link-color": "#99c794",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "cobalt2",
    name: "Cobalt2",
    type: "dark",
    monacoTheme: "theme-cobalt2",
    themeData: cobalt2Data,
    previewBg: "#193549",
    previewAccent: "#ffc600",
    cssVars: {
      "--bg-base": "#193549",
      "--bg-secondary": "#122637",
      "--bg-tertiary": "#1f4662",
      "--bg-hover": "rgba(255,255,255,0.05)",
      "--bg-elevated": "#1d3d55",
      "--border": "#1f4662",
      "--border-color": "#1f4662",
      "--text-primary": "#ffffff",
      "--text-secondary": "#80b1d0",
      "--text-tertiary": "#1f4662",
      "--primary": "#ffc600",
      "--primary-dark": "#e6b200",
      "--user-message-text": "#ffc600",
      "--link-color": "#9effff",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    type: "dark",
    monacoTheme: "theme-solarized-dark",
    themeData: solarizedDarkData,
    previewBg: "#002b36",
    previewAccent: "#268bd2",
    cssVars: {
      "--bg-base": "#002b36",
      "--bg-secondary": "#073642",
      "--bg-tertiary": "#083f4d",
      "--bg-hover": "rgba(255,255,255,0.04)",
      "--bg-elevated": "#054050",
      "--border": "#586e75",
      "--border-color": "#586e75",
      "--text-primary": "#93a1a1",
      "--text-secondary": "#657b83",
      "--text-tertiary": "#586e75",
      "--primary": "#268bd2",
      "--primary-dark": "#1a79c0",
      "--user-message-text": "#268bd2",
      "--link-color": "#2aa198",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    type: "dark",
    monacoTheme: "theme-github-dark",
    themeData: githubDarkData,
    previewBg: "#0d1117",
    previewAccent: "#58a6ff",
    cssVars: {
      "--bg-base": "#0d1117",
      "--bg-secondary": "#161b22",
      "--bg-tertiary": "#21262d",
      "--bg-hover": "rgba(255,255,255,0.04)",
      "--bg-elevated": "#161b22",
      "--border": "#30363d",
      "--border-color": "#30363d",
      "--text-primary": "#c9d1d9",
      "--text-secondary": "#8b949e",
      "--text-tertiary": "#484f58",
      "--primary": "#58a6ff",
      "--primary-dark": "#388bfd",
      "--user-message-text": "#58a6ff",
      "--link-color": "#58a6ff",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "tomorrow-night-eighties",
    name: "Tomorrow Night 80s",
    type: "dark",
    monacoTheme: "theme-tomorrow-night-eighties",
    themeData: tomorrowNightEightiesData,
    previewBg: "#2d2d2d",
    previewAccent: "#cc99cd",
    cssVars: {
      "--bg-base": "#2d2d2d",
      "--bg-secondary": "#222222",
      "--bg-tertiary": "#393939",
      "--bg-hover": "rgba(255,255,255,0.05)",
      "--bg-elevated": "#333333",
      "--border": "#515151",
      "--border-color": "#515151",
      "--text-primary": "#cccccc",
      "--text-secondary": "#999999",
      "--text-tertiary": "#515151",
      "--primary": "#6699cc",
      "--primary-dark": "#5588bb",
      "--user-message-text": "#cc99cd",
      "--link-color": "#6699cc",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "merbivore-soft",
    name: "Merbivore Soft",
    type: "dark",
    monacoTheme: "theme-merbivore-soft",
    themeData: merbivoreData,
    previewBg: "#1c1c1c",
    previewAccent: "#f08048",
    cssVars: {
      "--bg-base": "#1c1c1c",
      "--bg-secondary": "#0f0f0f",
      "--bg-tertiary": "#2a2a2a",
      "--bg-hover": "rgba(255,255,255,0.05)",
      "--bg-elevated": "#222222",
      "--border": "#3a3a3a",
      "--border-color": "#3a3a3a",
      "--text-primary": "#e6e1dc",
      "--text-secondary": "#998f84",
      "--text-tertiary": "#3a3a3a",
      "--primary": "#f08048",
      "--primary-dark": "#e06030",
      "--user-message-text": "#f08048",
      "--link-color": "#f08048",
      ...DARK_SEMANTIC,
    },
  },
];

// ─── Light theme definitions ─────────────────────────────────────────────────

export const LIGHT_COLOR_THEMES: ColorTheme[] = [
  {
    id: "github-light",
    name: "GitHub Light",
    type: "light",
    monacoTheme: "theme-github-light",
    themeData: githubLightData,
    previewBg: "#ffffff",
    previewAccent: "#0969da",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f6f8fa",
      "--bg-tertiary": "#eaeef2",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#d0d7de",
      "--border-color": "#d0d7de",
      "--text-primary": "#1f2328",
      "--text-secondary": "#57606a",
      "--text-tertiary": "#8c959f",
      "--primary": "#0969da",
      "--primary-dark": "#0860ca",
      "--user-message-text": "#0969da",
      "--link-color": "#0969da",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    type: "light",
    monacoTheme: "theme-solarized-light",
    themeData: solarizedLightData,
    previewBg: "#fdf6e3",
    previewAccent: "#268bd2",
    cssVars: {
      "--bg-base": "#fdf6e3",
      "--bg-secondary": "#eee8d5",
      "--bg-tertiary": "#e3ddc9",
      "--bg-hover": "rgba(0,0,0,0.05)",
      "--bg-elevated": "#fdf6e3",
      "--border": "#93a1a1",
      "--border-color": "#93a1a1",
      "--text-primary": "#657b83",
      "--text-secondary": "#839496",
      "--text-tertiary": "#93a1a1",
      "--primary": "#268bd2",
      "--primary-dark": "#1a7cc2",
      "--user-message-text": "#268bd2",
      "--link-color": "#2aa198",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "tomorrow",
    name: "Tomorrow",
    type: "light",
    monacoTheme: "theme-tomorrow",
    themeData: tomorrowData,
    previewBg: "#ffffff",
    previewAccent: "#4271ae",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f7f7f7",
      "--bg-tertiary": "#efefef",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#e0e0e0",
      "--border-color": "#e0e0e0",
      "--text-primary": "#4d4d4c",
      "--text-secondary": "#8e908c",
      "--text-tertiary": "#c8c8c8",
      "--primary": "#4271ae",
      "--primary-dark": "#3560a0",
      "--user-message-text": "#4271ae",
      "--link-color": "#718c00",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "xcode",
    name: "Xcode Default",
    type: "light",
    monacoTheme: "theme-xcode",
    themeData: xcodeData,
    previewBg: "#ffffff",
    previewAccent: "#0070c9",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f5f5f5",
      "--bg-tertiary": "#ebebeb",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#d9d9d9",
      "--border-color": "#d9d9d9",
      "--text-primary": "#000000",
      "--text-secondary": "#666666",
      "--text-tertiary": "#aaaaaa",
      "--primary": "#0070c9",
      "--primary-dark": "#005faa",
      "--user-message-text": "#0070c9",
      "--link-color": "#0070c9",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "textmate",
    name: "Textmate",
    type: "light",
    monacoTheme: "theme-textmate",
    themeData: textmateData,
    previewBg: "#f8f8f8",
    previewAccent: "#316bcd",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f8f8f8",
      "--bg-tertiary": "#f0f0f0",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#d3d3d3",
      "--border-color": "#d3d3d3",
      "--text-primary": "#000000",
      "--text-secondary": "#666666",
      "--text-tertiary": "#aaaaaa",
      "--primary": "#316bcd",
      "--primary-dark": "#2558ba",
      "--user-message-text": "#316bcd",
      "--link-color": "#316bcd",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "dawn",
    name: "Dawn",
    type: "light",
    monacoTheme: "theme-dawn",
    themeData: dawnData,
    previewBg: "#f9f9f9",
    previewAccent: "#7b59d0",
    cssVars: {
      "--bg-base": "#f9f9f9",
      "--bg-secondary": "#efefef",
      "--bg-tertiary": "#e5e5e5",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#d0d0d0",
      "--border-color": "#d0d0d0",
      "--text-primary": "#323232",
      "--text-secondary": "#777777",
      "--text-tertiary": "#aaaaaa",
      "--primary": "#7b59d0",
      "--primary-dark": "#6a48bf",
      "--user-message-text": "#7b59d0",
      "--link-color": "#7b59d0",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "clouds",
    name: "Clouds",
    type: "light",
    monacoTheme: "theme-clouds",
    themeData: cloudsData,
    previewBg: "#ffffff",
    previewAccent: "#3d8fd1",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f9f9f9",
      "--bg-tertiary": "#f1f1f1",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#e0e0e0",
      "--border-color": "#e0e0e0",
      "--text-primary": "#000000",
      "--text-secondary": "#888888",
      "--text-tertiary": "#c0c0c0",
      "--primary": "#3d8fd1",
      "--primary-dark": "#2d7ec0",
      "--user-message-text": "#3d8fd1",
      "--link-color": "#3d8fd1",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "iplastic",
    name: "iPlastic",
    type: "light",
    monacoTheme: "theme-iplastic",
    themeData: iPlasticData,
    previewBg: "#eeeeee",
    previewAccent: "#6c63ff",
    cssVars: {
      "--bg-base": "#eeeeee",
      "--bg-secondary": "#e4e4e4",
      "--bg-tertiary": "#d8d8d8",
      "--bg-hover": "rgba(0,0,0,0.05)",
      "--bg-elevated": "#f4f4f4",
      "--border": "#cccccc",
      "--border-color": "#cccccc",
      "--text-primary": "#000000",
      "--text-secondary": "#555555",
      "--text-tertiary": "#999999",
      "--primary": "#6c63ff",
      "--primary-dark": "#5a52e0",
      "--user-message-text": "#6c63ff",
      "--link-color": "#6c63ff",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "kuroir",
    name: "Kuroir",
    type: "light",
    monacoTheme: "theme-kuroir",
    themeData: kuroirData,
    previewBg: "#e8e9e8",
    previewAccent: "#5c8a32",
    cssVars: {
      "--bg-base": "#e8e9e8",
      "--bg-secondary": "#dde0dd",
      "--bg-tertiary": "#d0d4d0",
      "--bg-hover": "rgba(0,0,0,0.05)",
      "--bg-elevated": "#f0f1f0",
      "--border": "#c0c4c0",
      "--border-color": "#c0c4c0",
      "--text-primary": "#1e1e1e",
      "--text-secondary": "#555555",
      "--text-tertiary": "#888888",
      "--primary": "#5c8a32",
      "--primary-dark": "#4a7228",
      "--user-message-text": "#5c8a32",
      "--link-color": "#5c8a32",
      ...LIGHT_SEMANTIC,
    },
  },
  {
    id: "dreamweaver",
    name: "Dreamweaver",
    type: "light",
    monacoTheme: "theme-dreamweaver",
    themeData: dreamweaverData,
    previewBg: "#ffffff",
    previewAccent: "#e06c00",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f5f5f5",
      "--bg-tertiary": "#ebebeb",
      "--bg-hover": "rgba(0,0,0,0.04)",
      "--bg-elevated": "#ffffff",
      "--border": "#dddddd",
      "--border-color": "#dddddd",
      "--text-primary": "#333333",
      "--text-secondary": "#666666",
      "--text-tertiary": "#aaaaaa",
      "--primary": "#e06c00",
      "--primary-dark": "#cc5f00",
      "--user-message-text": "#e06c00",
      "--link-color": "#e06c00",
      ...LIGHT_SEMANTIC,
    },
  },
];

// ─── Catppuccin (custom inline definitions) ──────────────────────────────────

const catppuccinMochaData: MonacoThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6c7086", fontStyle: "italic" },
    { token: "keyword", foreground: "cba6f7" },
    { token: "string", foreground: "a6e3a1" },
    { token: "number", foreground: "fab387" },
    { token: "type", foreground: "89b4fa" },
    { token: "class", foreground: "89b4fa" },
    { token: "function", foreground: "89dceb" },
    { token: "variable", foreground: "cdd6f4" },
    { token: "constant", foreground: "fab387" },
    { token: "operator", foreground: "89dceb" },
  ],
  colors: {
    "editor.background": "#1e1e2e",
    "editor.foreground": "#cdd6f4",
    "editorLineNumber.foreground": "#45475a",
    "editorLineNumber.activeForeground": "#cdd6f4",
    "editor.selectionBackground": "#313244",
    "editor.lineHighlightBackground": "#181825",
    "editorCursor.foreground": "#f5e0dc",
    "diffEditor.insertedTextBackground": "#a6e3a122",
    "diffEditor.removedTextBackground": "#f38ba822",
  },
};

const catppuccinLatteData: MonacoThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "comment", foreground: "9ca0b0", fontStyle: "italic" },
    { token: "keyword", foreground: "8839ef" },
    { token: "string", foreground: "40a02b" },
    { token: "number", foreground: "fe640b" },
    { token: "type", foreground: "1e66f5" },
    { token: "class", foreground: "1e66f5" },
    { token: "function", foreground: "04a5e5" },
    { token: "variable", foreground: "4c4f69" },
    { token: "constant", foreground: "fe640b" },
    { token: "operator", foreground: "04a5e5" },
  ],
  colors: {
    "editor.background": "#eff1f5",
    "editor.foreground": "#4c4f69",
    "editorLineNumber.foreground": "#bcc0cc",
    "editorLineNumber.activeForeground": "#4c4f69",
    "editor.selectionBackground": "#ccd0da",
    "editor.lineHighlightBackground": "#e6e9ef",
    "editorCursor.foreground": "#dc8a78",
    "diffEditor.insertedTextBackground": "#40a02b22",
    "diffEditor.removedTextBackground": "#d20f3922",
  },
};

export const CATPPUCCIN_THEMES: ColorTheme[] = [
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    type: "dark",
    monacoTheme: "theme-catppuccin-mocha",
    themeData: catppuccinMochaData,
    previewBg: "#1e1e2e",
    previewAccent: "#cba6f7",
    cssVars: {
      "--bg-base": "#1e1e2e",
      "--bg-secondary": "#181825",
      "--bg-tertiary": "#313244",
      "--bg-hover": "rgba(205,214,244,0.05)",
      "--bg-elevated": "#24273a",
      "--border": "#45475a",
      "--border-color": "#45475a",
      "--text-primary": "#cdd6f4",
      "--text-secondary": "#a6adc8",
      "--text-tertiary": "#585b70",
      "--primary": "#cba6f7",
      "--primary-dark": "#b48ef5",
      "--user-message-text": "#89b4fa",
      "--link-color": "#89b4fa",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    type: "light",
    monacoTheme: "theme-catppuccin-latte",
    themeData: catppuccinLatteData,
    previewBg: "#eff1f5",
    previewAccent: "#8839ef",
    cssVars: {
      "--bg-base": "#eff1f5",
      "--bg-secondary": "#e6e9ef",
      "--bg-tertiary": "#ccd0da",
      "--bg-hover": "rgba(76,79,105,0.05)",
      "--bg-elevated": "#ffffff",
      "--border": "#bcc0cc",
      "--border-color": "#bcc0cc",
      "--text-primary": "#4c4f69",
      "--text-secondary": "#6c6f85",
      "--text-tertiary": "#9ca0b0",
      "--primary": "#8839ef",
      "--primary-dark": "#7527d0",
      "--user-message-text": "#1e66f5",
      "--link-color": "#1e66f5",
      ...LIGHT_SEMANTIC,
    },
  },
];

// ─── High Contrast (built-in Monaco themes, no defineTheme needed) ────────────

export const HIGH_CONTRAST_THEMES: ColorTheme[] = [
  {
    id: "hc-black",
    name: "High Contrast Dark",
    type: "dark",
    monacoTheme: "hc-black",
    themeData: null,
    previewBg: "#000000",
    previewAccent: "#6fc3df",
    cssVars: {
      "--bg-base": "#000000",
      "--bg-secondary": "#0a0a0a",
      "--bg-tertiary": "#1a1a1a",
      "--bg-hover": "rgba(255,255,255,0.08)",
      "--bg-elevated": "#111111",
      "--border": "#6fc3df",
      "--border-color": "#6fc3df",
      "--text-primary": "#ffffff",
      "--text-secondary": "#d4d4d4",
      "--text-tertiary": "#808080",
      "--primary": "#6fc3df",
      "--primary-dark": "#4ea8c8",
      "--user-message-text": "#6fc3df",
      "--link-color": "#6fc3df",
      ...DARK_SEMANTIC,
    },
  },
  {
    id: "hc-light",
    name: "High Contrast Light",
    type: "light",
    monacoTheme: "hc-light",
    themeData: null,
    previewBg: "#ffffff",
    previewAccent: "#0f4a85",
    cssVars: {
      "--bg-base": "#ffffff",
      "--bg-secondary": "#f5f5f5",
      "--bg-tertiary": "#e8e8e8",
      "--bg-hover": "rgba(0,0,0,0.08)",
      "--bg-elevated": "#ffffff",
      "--border": "#0f4a85",
      "--border-color": "#0f4a85",
      "--text-primary": "#000000",
      "--text-secondary": "#1a1a1a",
      "--text-tertiary": "#444444",
      "--primary": "#0f4a85",
      "--primary-dark": "#0a3a6e",
      "--user-message-text": "#0f4a85",
      "--link-color": "#0f4a85",
      ...LIGHT_SEMANTIC,
    },
  },
];

export const ALL_COLOR_THEMES = [
  ...DARK_COLOR_THEMES,
  ...LIGHT_COLOR_THEMES,
  ...CATPPUCCIN_THEMES,
  ...HIGH_CONTRAST_THEMES,
];

export function getColorThemeById(id: string): ColorTheme | undefined {
  return ALL_COLOR_THEMES.find((t) => t.id === id);
}

export function defineAllMonacoThemes(monaco: typeof import("monaco-editor")): void {
  for (const theme of ALL_COLOR_THEMES) {
    if (theme.themeData !== null) {
      monaco.editor.defineTheme(theme.monacoTheme, theme.themeData);
    }
    // Built-in Monaco themes (hc-black, hc-light) don't need defineTheme
  }
}
