version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: percy
    binary: percy
    main: ./cmd/percy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/tgruben-circuit/percy/version.Version={{ .Version }}
      - -X github.com/tgruben-circuit/percy/version.Tag={{ .Tag }}

archives:
  - id: percy
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

release:
  github:
    owner: tgruben-circuit
    name: percy
  draft: false
  prerelease: auto

homebrew_casks:
  - name: percy
    binaries:
      - percy
    repository:
      owner: tgruben-circuit
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/tgruben-circuit/percy
    description: "A mobile-friendly, web-based, multi-modal coding agent"
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{caskroom_path}"]
